import { describe, expect, it } from "bun:test";
import { OpenAPIHono } from "@hono/zod-openapi";
import { sign as jwtSign } from "hono/jwt";
import { onError } from "../../error/on-error";
import { traceIdMiddleware } from "../../middleware/trace-id";
import { env } from "../../env";
import { createAuthApp } from "./auth.route";
import { findUserByEmail, registerUser } from "./user-store";
import { ACCESS_TOKEN_COOKIE } from "./require-auth.middleware";

function uniqueEmail(label: string) { return `${label}-${crypto.randomUUID()}@example.com`; }
function buildTestApp() { const app = new OpenAPIHono(); app.use("*", traceIdMiddleware); app.onError(onError); app.route("/", createAuthApp()); return app; }
function extractCookieValue(setCookieHeader: string | null, name: string): string | undefined { if (!setCookieHeader) return undefined; return setCookieHeader.split(";").map((part) => part.trim()).find((part) => part.startsWith(`${name}=`))?.slice(name.length + 1); }

describe("auth module", () => {
  it("registers + logs in successfully, setting an httpOnly/SameSite=Lax cookie", async () => { const app = buildTestApp(); const email = uniqueEmail("ada"); const registerRes = await app.request("/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password: "correct horse battery" }) }); expect(registerRes.status).toBe(201); const loginRes = await app.request("/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password: "correct horse battery" }) }); expect(loginRes.status).toBe(200); expect(((await loginRes.json()) as { ok: boolean }).ok).toBe(true); const setCookie = loginRes.headers.get("Set-Cookie"); expect(setCookie).toBeTruthy(); expect(setCookie).toContain("HttpOnly"); expect(setCookie).toContain("SameSite=Lax"); expect(setCookie).toContain("Secure"); expect(setCookie?.startsWith(`${ACCESS_TOKEN_COOKIE}=`)).toBe(true); });
  it("returns BYTE-IDENTICAL responses for unknown-user vs wrong-password", async () => { const app = buildTestApp(); const email = uniqueEmail("grace"); await registerUser(email, "the-real-password"); const unknownUserRes = await app.request("/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: uniqueEmail("nobody"), password: "whatever" }) }); const wrongPasswordRes = await app.request("/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password: "wrong-password" }) }); expect(unknownUserRes.status).toBe(401); expect(wrongPasswordRes.status).toBe(401); const unknownUserBody = JSON.parse(await unknownUserRes.text()) as Record<string, unknown>; const wrongPasswordBody = JSON.parse(await wrongPasswordRes.text()) as Record<string, unknown>; const { traceId: _unknownTraceId, ...unknownRest } = unknownUserBody; const { traceId: _wrongTraceId, ...wrongRest } = wrongPasswordBody; expect(typeof _unknownTraceId).toBe("string"); expect(typeof _wrongTraceId).toBe("string"); expect(JSON.stringify(unknownRest)).toBe(JSON.stringify(wrongRest)); expect(unknownUserBody.code).toBe("auth/INVALID_CREDENTIALS"); });
  it("rejects missing, malformed, and expired cookies on protected route", async () => { const app = buildTestApp(); const missing = await app.request("/auth/me"); expect(missing.status).toBe(401); expect(((await missing.json()) as { code: string }).code).toBe("auth/UNAUTHENTICATED"); const malformed = await app.request("/auth/me", { headers: { Cookie: `${ACCESS_TOKEN_COOKIE}=not-a-real-jwt` } }); expect(malformed.status).toBe(401); expect(((await malformed.json()) as { code: string }).code).toBe("auth/UNAUTHENTICATED"); const now = Math.floor(Date.now() / 1000); const expiredToken = await jwtSign({ sub: uniqueEmail("expired"), iat: now - 3600, exp: now - 60 }, env.JWT_SECRET as string); const expired = await app.request("/auth/me", { headers: { Cookie: `${ACCESS_TOKEN_COOKIE}=${expiredToken}` } }); expect(expired.status).toBe(401); expect(((await expired.json()) as { code: string }).code).toBe("auth/SESSION_EXPIRED"); });
  it("returns 200 with the authenticated identity for a valid token", async () => { const app = buildTestApp(); const email = uniqueEmail("turing"); await registerUser(email, "enigma-breaker"); const loginRes = await app.request("/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password: "enigma-breaker" }) }); const token = extractCookieValue(loginRes.headers.get("Set-Cookie"), ACCESS_TOKEN_COOKIE); expect(token).toBeTruthy(); const meRes = await app.request("/auth/me", { headers: { Cookie: `${ACCESS_TOKEN_COOKIE}=${token}` } }); expect(meRes.status).toBe(200); const body = (await meRes.json()) as { email: string; role: string }; expect(body.email).toBe(email); expect(body.role).toBe("worker"); });
  it("never stores the plaintext password", async () => { const plaintext = "super-secret-plaintext"; const email = uniqueEmail("hopper"); await registerUser(email, plaintext); const stored = await findUserByEmail(email); expect(stored).toBeDefined(); expect(stored?.passwordHash).not.toBe(plaintext); expect(stored?.passwordHash.startsWith("$argon2id$")).toBe(true); });
  it("trips the auth-specific rate limit before the global limiter would", async () => { const app = buildTestApp(); const statuses: number[] = []; for (let i = 0; i < 11; i++) { const res = await app.request("/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: uniqueEmail("rate-limit-probe"), password: "whatever" }) }); statuses.push(res.status); } expect(statuses.length).toBe(11); expect(statuses[10]).toBe(429); expect(statuses.slice(0, 10).every((s) => s !== 429)).toBe(true); });
});
