import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { deleteCookie, setCookie } from "hono/cookie";
import { rateLimit } from "../../middleware/rate-limit";
import { ValidationError } from "../../error/validation-error";
import { AuthenticationError } from "./auth.errors";
import { ACCESS_TOKEN_TTL_SECONDS, issueAccessToken } from "./jwt";
import { ACCESS_TOKEN_COOKIE, requireAuth, requireRole, type RequireAuthVariables } from "./require-auth.middleware";
import { createUser, findUserByUsernameOrEmail, registerUser, resetUserPassword, updateUser } from "./user-store";

const DUMMY_PASSWORD_HASH = Bun.password.hashSync("dummy-password-used-only-for-timing-parity", { algorithm: "argon2id" });
const roleSchema = z.enum(["owner", "pm", "worker"]);
const credentialsBodySchema = z.object({ email: z.string().email(), password: z.string().min(1) });
const loginBodySchema = z.object({ identifier: z.string().min(1).optional(), email: z.string().min(1).optional(), password: z.string().min(1) });
const userBodySchema = z.object({ email: z.string().email(), username: z.string().min(1), name: z.string().optional(), role: roleSchema, password: z.string().min(8) });
const updateUserBodySchema = z.object({ email: z.string().email().optional(), username: z.string().min(1).optional(), name: z.string().nullable().optional(), role: roleSchema.optional() });
const resetPasswordBodySchema = z.object({ password: z.string().min(8) });
function throwOnValidationFailure(result: { success: boolean; error?: { issues: { path: (string | number)[]; message: string }[] } }): undefined { if (!result.success && result.error) { const fields: Record<string, string[]> = {}; for (const issue of result.error.issues) (fields[issue.path.length ? issue.path.join(".") : "(root)"] ??= []).push(issue.message); throw new ValidationError(fields); } }
const registerRoute = createRoute({ method: "post", path: "/auth/register", request: { body: { content: { "application/json": { schema: credentialsBodySchema } } } }, responses: { 201: { description: "User registered.", content: { "application/json": { schema: z.object({ email: z.string() }) } } } } });
const loginRoute = createRoute({ method: "post", path: "/auth/login", request: { body: { content: { "application/json": { schema: loginBodySchema } } } }, responses: { 200: { description: "Login succeeded.", content: { "application/json": { schema: z.object({ ok: z.literal(true) }) } } } } });
const meRoute = createRoute({ method: "get", path: "/auth/me", responses: { 200: { description: "Identity.", content: { "application/json": { schema: z.object({ email: z.string(), role: roleSchema }) } } } } });
const createUserRoute = createRoute({ method: "post", path: "/users", request: { body: { content: { "application/json": { schema: userBodySchema } } } }, responses: { 201: { description: "User created.", content: { "application/json": { schema: z.object({ id: z.string(), email: z.string(), username: z.string(), role: roleSchema }) } } } } });
const updateUserRoute = createRoute({ method: "patch", path: "/users/{id}", request: { params: z.object({ id: z.string() }), body: { content: { "application/json": { schema: updateUserBodySchema } } } }, responses: { 200: { description: "User updated.", content: { "application/json": { schema: z.object({ id: z.string(), email: z.string(), username: z.string(), role: roleSchema }) } } } } });
const resetPasswordRoute = createRoute({ method: "post", path: "/users/{id}/reset-password", request: { params: z.object({ id: z.string() }), body: { content: { "application/json": { schema: resetPasswordBodySchema } } } }, responses: { 200: { description: "Password reset.", content: { "application/json": { schema: z.object({ id: z.string(), email: z.string(), username: z.string(), role: roleSchema }) } } } } });
export function createAuthApp() { const authApp = new OpenAPIHono<{ Variables: RequireAuthVariables }>(); authApp.use("/auth/*", rateLimit({ windowMs: 60_000, max: 10 })); authApp.openapi(registerRoute, async (c) => { const { email, password } = c.req.valid("json"); const user = await registerUser(email, password); return c.json({ email: user.email }, 201); }, throwOnValidationFailure); authApp.openapi(loginRoute, async (c) => { const body = c.req.valid("json"); const identifier = body.identifier ?? body.email; if (!identifier) throw new ValidationError({ identifier: ["identifier or email is required"] }); const user = await findUserByUsernameOrEmail(identifier); const passwordMatches = await Bun.password.verify(body.password, user?.passwordHash ?? DUMMY_PASSWORD_HASH); if (!user || !passwordMatches) throw new AuthenticationError(); const token = await issueAccessToken(user.email); setCookie(c, ACCESS_TOKEN_COOKIE, token, { httpOnly: true, sameSite: "Lax", secure: true, path: "/", maxAge: ACCESS_TOKEN_TTL_SECONDS }); return c.json({ ok: true as const }, 200); }, throwOnValidationFailure); authApp.use("/auth/me", requireAuth); authApp.openapi(meRoute, (c) => { const user = c.get("authUser"); return c.json({ email: user.email, role: user.role }, 200); }); authApp.post("/auth/logout", (c) => { deleteCookie(c, ACCESS_TOKEN_COOKIE, { path: "/" }); return c.json({ ok: true as const }, 200); }); authApp.use("/users/*", requireAuth, requireRole(["owner"])); authApp.openapi(createUserRoute, async (c) => c.json(await createUser(c.req.valid("json")), 201), throwOnValidationFailure); authApp.openapi(updateUserRoute, async (c) => c.json(await updateUser(c.req.valid("param").id, c.req.valid("json")), 200), throwOnValidationFailure); authApp.openapi(resetPasswordRoute, async (c) => c.json(await resetUserPassword(c.req.valid("param").id, c.req.valid("json").password), 200), throwOnValidationFailure); return authApp; }
export const authApp = createAuthApp();
