import { Prisma, type User, type UserRole } from "@prisma/client";
import { AppError } from "../../error/app-error";
import { prisma } from "../../db/prisma";

export type PublicUser = Pick<User, "id" | "email" | "username" | "name" | "role" | "createdAt" | "updatedAt">;
export type StoredUser = PublicUser & { passwordHash: string };

function normalize(value: string): string { return value.trim().toLowerCase(); }
function conflictError(): AppError { return new AppError("common/VALIDATION_FAILED", "User email or username already exists", { status: 409, details: { fields: { email: ["email or username already exists"] } } }); }
export function publicUser(user: User): PublicUser { const { passwordHash: _passwordHash, ...publicUser } = user; return publicUser; }
export async function registerUser(email: string, password: string, options?: { username?: string; name?: string; role?: UserRole }): Promise<StoredUser> { const normalizedEmail = normalize(email); const username = normalize(options?.username ?? normalizedEmail.split("@")[0] ?? normalizedEmail); const passwordHash = await Bun.password.hash(password, { algorithm: "argon2id" }); try { return await prisma.user.create({ data: { email: normalizedEmail, username, name: options?.name, role: options?.role ?? "worker", passwordHash } }); } catch (err) { if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002") throw conflictError(); throw err; } }
export async function findUserByEmail(email: string): Promise<StoredUser | undefined> { return (await prisma.user.findUnique({ where: { email: normalize(email) } })) ?? undefined; }
export async function findUserByUsernameOrEmail(identifier: string): Promise<StoredUser | undefined> { const normalized = normalize(identifier); return (await prisma.user.findFirst({ where: { OR: [{ email: normalized }, { username: normalized }] } })) ?? undefined; }
export async function createUser(input: { email: string; username: string; password: string; name?: string; role: UserRole }): Promise<PublicUser> { return publicUser(await registerUser(input.email, input.password, { username: input.username, name: input.name, role: input.role })); }
export async function updateUser(id: string, input: { email?: string; username?: string; name?: string | null; role?: UserRole }): Promise<PublicUser> { try { return publicUser(await prisma.user.update({ where: { id }, data: { email: input.email === undefined ? undefined : normalize(input.email), username: input.username === undefined ? undefined : normalize(input.username), name: input.name, role: input.role } })); } catch (err) { if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002") throw conflictError(); if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2025") throw new AppError("common/NOT_FOUND", "User not found", { status: 404 }); throw err; } }
export async function resetUserPassword(id: string, password: string): Promise<PublicUser> { const passwordHash = await Bun.password.hash(password, { algorithm: "argon2id" }); try { return publicUser(await prisma.user.update({ where: { id }, data: { passwordHash } })); } catch (err) { if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2025") throw new AppError("common/NOT_FOUND", "User not found", { status: 404 }); throw err; } }
export async function __resetUserStoreForTests(): Promise<void> { await prisma.attachment.deleteMany(); await prisma.expenseItem.deleteMany(); await prisma.expense.deleteMany(); await prisma.project.deleteMany(); await prisma.user.deleteMany(); }
