import { afterAll, beforeEach, describe, expect, it } from "bun:test";
import { OpenAPIHono } from "@hono/zod-openapi";
import { onError } from "../../error/on-error";
import { traceIdMiddleware } from "../../middleware/trace-id";
import { prisma } from "../../db/prisma";
import { createAuthApp } from "../auth/auth.route";
import { createUser, registerUser } from "../auth/user-store";
import { ACCESS_TOKEN_COOKIE } from "../auth/require-auth.middleware";
import { projectsApp } from "./projects.route";

function buildTestApp() { const app = new OpenAPIHono(); app.use("*", traceIdMiddleware); app.onError(onError); app.route("/", createAuthApp()); app.route("/", projectsApp); return app; }
async function resetDb() { await prisma.attachment.deleteMany(); await prisma.expenseItem.deleteMany(); await prisma.expense.deleteMany(); await prisma.project.deleteMany(); await prisma.user.deleteMany(); }
function cookie(header: string | null) { return `${ACCESS_TOKEN_COOKIE}=${header?.split(";")[0].split("=")[1]}`; }
async function login(app: OpenAPIHono, email: string, password: string) { const res = await app.request("/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); expect(res.status).toBe(200); return cookie(res.headers.get("Set-Cookie")); }
async function seedUsers(app: OpenAPIHono) { await registerUser("owner@example.com", "password123", { username: "owner", role: "owner" }); const ownerCookie = await login(app, "owner@example.com", "password123"); const pm = await createUser({ email: "pm@example.com", username: "pm", role: "pm", password: "password123" }); const worker = await createUser({ email: "worker@example.com", username: "worker", role: "worker", password: "password123" }); const pmCookie = await login(app, pm.email, "password123"); const workerCookie = await login(app, worker.email, "password123"); return { ownerCookie, pmCookie, workerCookie, pm, worker }; }
async function createProject(app: OpenAPIHono, ownerCookie: string, estimate = 1000) { const res = await app.request("/projects", { method: "POST", headers: { "Content-Type": "application/json", Cookie: ownerCookie }, body: JSON.stringify({ name: "Kitchen", estimate }) }); expect(res.status).toBe(201); return (await res.json()) as { id: string; actual_to_date: number; variance_pct: number; estimate: number }; }
const expensePayload = { vendor: "Lumber Yard", category: "material", entryDate: "2026-09-01", tax: 5, fee: 2, totalAmount: 999999, items: [{ description: "Wood", quantity: 2, unitPrice: 10 }] };

beforeEach(resetDb);
afterAll(async () => { await prisma.$disconnect(); });

describe("variance board API", () => {
  it("supports owner-only user management without password-hash leakage", async () => { const app = buildTestApp(); await registerUser("owner@example.com", "password123", { username: "owner", role: "owner" }); const ownerCookie = await login(app, "owner", "password123"); const createRes = await app.request("/users", { method: "POST", headers: { "Content-Type": "application/json", Cookie: ownerCookie }, body: JSON.stringify({ email: "new@example.com", username: "newbie", role: "worker", password: "password123" }) }); expect(createRes.status).toBe(201); const body = await createRes.json() as Record<string, unknown>; expect(body.passwordHash).toBeUndefined(); const duplicate = await app.request("/users", { method: "POST", headers: { "Content-Type": "application/json", Cookie: ownerCookie }, body: JSON.stringify({ email: "new@example.com", username: "newbie2", role: "worker", password: "password123" }) }); expect(duplicate.status).toBe(409); const reset = await app.request(`/users/${body.id}/reset-password`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: ownerCookie }, body: JSON.stringify({ password: "changed123" }) }); expect(reset.status).toBe(200); expect((await login(app, "new@example.com", "changed123"))).toContain(ACCESS_TOKEN_COOKIE); });
  it("denies PM/worker user and project writes", async () => { const app = buildTestApp(); const { pmCookie, workerCookie } = await seedUsers(app); for (const authCookie of [pmCookie, workerCookie]) { const userRes = await app.request("/users", { method: "POST", headers: { "Content-Type": "application/json", Cookie: authCookie }, body: JSON.stringify({ email: crypto.randomUUID()+"@example.com", username: crypto.randomUUID(), role: "worker", password: "password123" }) }); expect(userRes.status).toBe(403); const projectRes = await app.request("/projects", { method: "POST", headers: { "Content-Type": "application/json", Cookie: authCookie }, body: JSON.stringify({ name: "Denied", estimate: 10 }) }); expect(projectRes.status).toBe(403); } });
  it("creates/lists project and rejects non-positive estimates", async () => { const app = buildTestApp(); const { ownerCookie } = await seedUsers(app); const bad = await app.request("/projects", { method: "POST", headers: { "Content-Type": "application/json", Cookie: ownerCookie }, body: JSON.stringify({ name: "Bad", estimate: 0 }) }); expect(bad.status).toBe(400); const project = await createProject(app, ownerCookie); expect(project.actual_to_date).toBe(0); expect(project.variance_pct).toBe(-100); const list = await app.request("/projects", { headers: { Cookie: ownerCookie } }); expect(list.status).toBe(200); expect(((await list.json()) as { projects: unknown[] }).projects.length).toBe(1); });
  it("calculates expense totals server-side and updates variance", async () => { const app = buildTestApp(); const { ownerCookie, pmCookie, workerCookie } = await seedUsers(app); const project = await createProject(app, ownerCookie, 100); const workerWrite = await app.request(`/projects/${project.id}/expenses`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: workerCookie }, body: JSON.stringify(expensePayload) }); expect(workerWrite.status).toBe(403); const create = await app.request(`/projects/${project.id}/expenses`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify(expensePayload) }); expect(create.status).toBe(201); const expense = await create.json() as { id: string; totalAmount: number; subtotal: number; updatedAt: string }; expect(expense.subtotal).toBe(20); expect(expense.totalAmount).toBe(27); const read = await app.request(`/expenses/${expense.id}`, { headers: { Cookie: workerCookie } }); expect(read.status).toBe(200); const detail = await app.request(`/projects/${project.id}`, { headers: { Cookie: ownerCookie } }); const detailBody = await detail.json() as { project: { actual_to_date: number; variance_pct: number } }; expect(detailBody.project.actual_to_date).toBe(27); expect(detailBody.project.variance_pct).toBe(-73); });
  it("handles optimistic locking and soft-delete recomputation", async () => { const app = buildTestApp(); const { ownerCookie, pmCookie, workerCookie } = await seedUsers(app); const project = await createProject(app, ownerCookie, 100); const create = await app.request(`/projects/${project.id}/expenses`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify(expensePayload) }); const expense = await create.json() as { id: string; updatedAt: string }; const stale = await app.request(`/expenses/${expense.id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify({ ...expensePayload, updatedAt: "2000-01-01T00:00:00.000Z" }) }); expect(stale.status).toBe(409); const edit = await app.request(`/expenses/${expense.id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify({ ...expensePayload, tax: 0, fee: 0, items: [{ description: "Labor", quantity: 3, unitPrice: 10 }], updatedAt: expense.updatedAt }) }); expect(edit.status).toBe(200); expect(((await edit.json()) as { totalAmount: number }).totalAmount).toBe(30); const pmDelete = await app.request(`/expenses/${expense.id}`, { method: "DELETE", headers: { Cookie: pmCookie } }); expect(pmDelete.status).toBe(403); const workerDelete = await app.request(`/expenses/${expense.id}`, { method: "DELETE", headers: { Cookie: workerCookie } }); expect(workerDelete.status).toBe(403); const del = await app.request(`/expenses/${expense.id}`, { method: "DELETE", headers: { Cookie: ownerCookie } }); expect(del.status).toBe(200); const detail = await app.request(`/projects/${project.id}`, { headers: { Cookie: ownerCookie } }); expect(((await detail.json()) as { project: { actual_to_date: number } }).project.actual_to_date).toBe(0); });
  it("validates attachment metadata limits", async () => { const app = buildTestApp(); const { ownerCookie, pmCookie } = await seedUsers(app); const project = await createProject(app, ownerCookie, 100); const create = await app.request(`/projects/${project.id}/expenses`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify(expensePayload) }); const expense = await create.json() as { id: string }; const badType = await app.request(`/expenses/${expense.id}/attachments`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify({ files: [{ filename: "x.exe", contentType: "application/octet-stream", sizeBytes: 1 }] }) }); expect(badType.status).toBe(400); const tooBig = await app.request(`/expenses/${expense.id}/attachments`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify({ files: [{ filename: "x.pdf", contentType: "application/pdf", sizeBytes: 11 * 1024 * 1024 }] }) }); expect(tooBig.status).toBe(400); const ok = await app.request(`/expenses/${expense.id}/attachments`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: pmCookie }, body: JSON.stringify({ files: [{ filename: "x.pdf", contentType: "application/pdf", sizeBytes: 100 }] }) }); expect(ok.status).toBe(201); });
});
