import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { Prisma } from "@prisma/client";
import { AppError } from "../../error/app-error";
import { ValidationError } from "../../error/validation-error";
import { prisma } from "../../db/prisma";
import { requireAuth, requireRole, type RequireAuthVariables } from "../auth/require-auth.middleware";
import { publishDirtyBucket } from "../events/events";
import { ALLOWED_ATTACHMENT_TYPES, MAX_ATTACHMENT_BYTES, MAX_ATTACHMENTS_PER_EXPENSE, memoryAttachmentStorage } from "../attachments/storage";
import { toNumber, variancePct } from "./variance";

const statusSchema = z.enum(["active", "archived"]);
const categorySchema = z.enum(["material", "labor", "equipment", "other"]);
const projectBodySchema = z.object({ name: z.string().min(1), estimate: z.coerce.number().positive(), status: statusSchema.default("active") });
const itemSchema = z.object({ description: z.string().min(1), quantity: z.coerce.number().positive(), unitPrice: z.coerce.number().nonnegative() });
const expenseBodySchema = z.object({ vendor: z.string().min(1), category: categorySchema, entryDate: z.string().min(1), note: z.string().optional(), tax: z.coerce.number().nonnegative().default(0), fee: z.coerce.number().nonnegative().default(0), items: z.array(itemSchema).min(1) });
const expensePatchSchema = expenseBodySchema.extend({ updatedAt: z.string().min(1) });
const attachmentBodySchema = z.object({ files: z.array(z.object({ filename: z.string().min(1), contentType: z.string().min(1), sizeBytes: z.number().int().positive() })).min(1).max(MAX_ATTACHMENTS_PER_EXPENSE) });
function throwOnValidationFailure(result: { success: boolean; error?: { issues: { path: (string | number)[]; message: string }[] } }): undefined { if (!result.success && result.error) { const fields: Record<string, string[]> = {}; for (const issue of result.error.issues) (fields[issue.path.length ? issue.path.join(".") : "(root)"] ??= []).push(issue.message); throw new ValidationError(fields); } }
function notFound(message = "Not found") { return new AppError("common/NOT_FOUND", message, { status: 404 }); }
function serializeProject(project: any, actual: Prisma.Decimal | number) { const estimate = toNumber(project.estimate); const actualToDate = toNumber(actual); return { id: project.id, name: project.name, estimate, status: project.status, actual_to_date: actualToDate, variance_pct: variancePct(actualToDate, estimate), createdAt: project.createdAt, updatedAt: project.updatedAt }; }
async function actualForProject(projectId: string) { const sum = await prisma.expense.aggregate({ where: { projectId, deletedAt: null }, _sum: { totalAmount: true } }); return sum._sum.totalAmount ?? new Prisma.Decimal(0); }
async function serializeExpense(expense: any) { return { id: expense.id, projectId: expense.projectId, vendor: expense.vendor, category: expense.category, entryDate: expense.entryDate.toISOString().slice(0,10), note: expense.note, subtotal: toNumber(expense.subtotal), tax: toNumber(expense.tax), fee: toNumber(expense.fee), totalAmount: toNumber(expense.totalAmount), updatedAt: expense.updatedAt.toISOString(), deletedAt: expense.deletedAt?.toISOString() ?? null, items: (expense.items ?? []).map((item: any) => ({ id: item.id, description: item.description, quantity: toNumber(item.quantity), unitPrice: toNumber(item.unitPrice), amount: toNumber(item.amount) })), attachments: (expense.attachments ?? []).map((a: any) => ({ id: a.id, filename: a.filename, contentType: a.contentType, sizeBytes: a.sizeBytes })) }; }
function totals(items: { description: string; quantity: number; unitPrice: number }[], tax: number, fee: number) { const computed = items.map((item) => ({ ...item, amount: new Prisma.Decimal(item.quantity).mul(item.unitPrice) })); const subtotal = computed.reduce((sum, item) => sum.add(item.amount), new Prisma.Decimal(0)); const total = subtotal.add(tax).add(fee); return { computed, subtotal, total }; }
async function getReadableExpense(id: string) { const expense = await prisma.expense.findUnique({ where: { id }, include: { items: true, attachments: true } }); if (!expense) throw notFound("Expense not found"); return expense; }
export const projectsApp = new OpenAPIHono<{ Variables: RequireAuthVariables }>();
projectsApp.use("/projects/*", requireAuth);
projectsApp.use("/expenses/*", requireAuth);
projectsApp.get("/projects", async (c) => { const projects = await prisma.project.findMany({ where: { status: "active" }, orderBy: { createdAt: "desc" } }); const items = await Promise.all(projects.map(async (p) => serializeProject(p, await actualForProject(p.id)))); return c.json({ projects: items }, 200); });
projectsApp.openapi(createRoute({ method: "post", path: "/projects", request: { body: { content: { "application/json": { schema: projectBodySchema } } } }, responses: { 201: { description: "Project created" } } }), async (c) => { await requireRole(["owner"])(c, async()=>{}); const body = c.req.valid("json"); const project = await prisma.project.create({ data: body }); return c.json(serializeProject(project, 0), 201); }, throwOnValidationFailure);
projectsApp.get("/projects/:id", async (c) => { const project = await prisma.project.findUnique({ where: { id: c.req.param("id") }, include: { expenses: { where: { deletedAt: null }, include: { items: true, attachments: true }, orderBy: { entryDate: "desc" } } } }); if (!project) throw notFound("Project not found"); return c.json({ project: serializeProject(project, await actualForProject(project.id)), expenses: await Promise.all(project.expenses.map(serializeExpense)) }, 200); });
projectsApp.openapi(createRoute({ method: "patch", path: "/projects/{id}", request: { params: z.object({ id: z.string() }), body: { content: { "application/json": { schema: projectBodySchema.partial().refine((v) => v.estimate === undefined || v.estimate > 0) } } } }, responses: { 200: { description: "Project updated" } } }), async (c) => { await requireRole(["owner"])(c, async()=>{}); try { const project = await prisma.project.update({ where: { id: c.req.valid("param").id }, data: c.req.valid("json") }); return c.json(serializeProject(project, await actualForProject(project.id)), 200); } catch (err) { if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2025") throw notFound("Project not found"); throw err; } }, throwOnValidationFailure);
projectsApp.openapi(createRoute({ method: "post", path: "/projects/{id}/expenses", request: { params: z.object({ id: z.string() }), body: { content: { "application/json": { schema: expenseBodySchema } } } }, responses: { 201: { description: "Expense created" } } }), async (c) => { await requireRole(["owner", "pm"])(c, async()=>{}); const body = c.req.valid("json"); const project = await prisma.project.findUnique({ where: { id: c.req.valid("param").id } }); if (!project) throw notFound("Project not found"); const calc = totals(body.items, body.tax, body.fee); const expense = await prisma.expense.create({ data: { projectId: project.id, createdById: c.get("authUser").id, vendor: body.vendor, category: body.category, entryDate: new Date(body.entryDate), note: body.note, subtotal: calc.subtotal, tax: body.tax, fee: body.fee, totalAmount: calc.total, items: { create: calc.computed.map((item) => ({ description: item.description, quantity: item.quantity, unitPrice: item.unitPrice, amount: item.amount })) } }, include: { items: true, attachments: true } }); publishDirtyBucket(`project:${project.id}`); return c.json(await serializeExpense(expense), 201); }, throwOnValidationFailure);
projectsApp.get("/expenses/:id", async (c) => c.json({ expense: await serializeExpense(await getReadableExpense(c.req.param("id"))) }, 200));
projectsApp.openapi(createRoute({ method: "patch", path: "/expenses/{id}", request: { params: z.object({ id: z.string() }), body: { content: { "application/json": { schema: expensePatchSchema } } } }, responses: { 200: { description: "Expense updated" }, 409: { description: "Conflict" } } }), async (c) => { await requireRole(["owner", "pm"])(c, async()=>{}); const id = c.req.valid("param").id; const body = c.req.valid("json"); const current = await prisma.expense.findUnique({ where: { id }, include: { items: true } }); if (!current) throw notFound("Expense not found"); if (current.updatedAt.toISOString() !== body.updatedAt) throw new AppError("common/VALIDATION_FAILED", "Expense was updated by another user", { status: 409 }); const calc = totals(body.items, body.tax, body.fee); const expense = await prisma.$transaction(async (tx) => { await tx.expenseItem.deleteMany({ where: { expenseId: id } }); return tx.expense.update({ where: { id }, data: { vendor: body.vendor, category: body.category, entryDate: new Date(body.entryDate), note: body.note, subtotal: calc.subtotal, tax: body.tax, fee: body.fee, totalAmount: calc.total, items: { create: calc.computed.map((item) => ({ description: item.description, quantity: item.quantity, unitPrice: item.unitPrice, amount: item.amount })) } }, include: { items: true, attachments: true } }); }); publishDirtyBucket(`project:${expense.projectId}`); return c.json(await serializeExpense(expense), 200); }, throwOnValidationFailure);
projectsApp.delete("/expenses/:id", async (c) => { await requireRole(["owner"])(c, async()=>{}); const current = await prisma.expense.findUnique({ where: { id: c.req.param("id") } }); if (!current) throw notFound("Expense not found"); const expense = await prisma.expense.update({ where: { id: current.id }, data: { deletedAt: new Date() } }); publishDirtyBucket(`project:${expense.projectId}`); return c.json({ ok: true }, 200); });
projectsApp.openapi(createRoute({ method: "post", path: "/expenses/{id}/attachments", request: { params: z.object({ id: z.string() }), body: { content: { "application/json": { schema: attachmentBodySchema } } } }, responses: { 201: { description: "Attachments saved" } } }), async (c) => { const expenseId = c.req.valid("param").id; const expense = await prisma.expense.findUnique({ where: { id: expenseId }, include: { attachments: true } }); if (!expense) throw notFound("Expense not found"); const { files } = c.req.valid("json"); if (expense.attachments.length + files.length > MAX_ATTACHMENTS_PER_EXPENSE) throw new ValidationError({ files: ["maximum 5 files per expense"] }); for (const file of files) { if (!ALLOWED_ATTACHMENT_TYPES.has(file.contentType)) throw new ValidationError({ contentType: ["unsupported attachment type"] }); if (file.sizeBytes > MAX_ATTACHMENT_BYTES) throw new ValidationError({ sizeBytes: ["file exceeds 10MB"] }); } const attachments = []; for (const file of files) { const key = `${expenseId}/${crypto.randomUUID()}-${file.filename}`; const stored = await memoryAttachmentStorage.save(new File([new Uint8Array()], file.filename, { type: file.contentType }), key); attachments.push(await prisma.attachment.create({ data: { expenseId, filename: file.filename, contentType: file.contentType, sizeBytes: file.sizeBytes, storageKey: stored.key } })); } return c.json({ attachments: attachments.map((a) => ({ id: a.id, filename: a.filename, contentType: a.contentType, sizeBytes: a.sizeBytes })) }, 201); }, throwOnValidationFailure);
projectsApp.get("/expenses/:id/attachments", async (c) => { const expense = await prisma.expense.findUnique({ where: { id: c.req.param("id") }, include: { attachments: true } }); if (!expense) throw notFound("Expense not found"); return c.json({ attachments: expense.attachments.map((a) => ({ id: a.id, filename: a.filename, contentType: a.contentType, sizeBytes: a.sizeBytes, url: `/attachments/${a.id}` })) }, 200); });
